In [1]:
import numpy as np

In [13]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3).reshape((3, 1))

In [15]:
a.shape

(3, 1)

In [3]:
print(a)
print(b)

[[0]
 [1]
 [2]]
[[0]
 [1]
 [2]]


In [4]:
# 縦(vertical)での連結
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.vstack.html
np.vstack((a, b))

array([[0],
       [1],
       [2],
       [0],
       [1],
       [2]])

In [5]:
# 横(horizontal)での連結
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.hstack.html
np.hstack((a, b))

array([[0, 0],
       [1, 1],
       [2, 2]])

In [6]:
# 深さ(depth)での連結
# https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.dstack.html
np.dstack((a, b))

array([[[0, 0]],

       [[1, 1]],

       [[2, 2]]])

In [14]:
np.dstack((a, b)).shape

(3, 1, 2)

In [7]:
a = np.arange(27).reshape((3, 3, 3))

In [8]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
b = np.arange(27).reshape((3, 3, 3))

In [10]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
np.dstack((a, b))

array([[[ 0,  1,  2,  0,  1,  2],
        [ 3,  4,  5,  3,  4,  5],
        [ 6,  7,  8,  6,  7,  8]],

       [[ 9, 10, 11,  9, 10, 11],
        [12, 13, 14, 12, 13, 14],
        [15, 16, 17, 15, 16, 17]],

       [[18, 19, 20, 18, 19, 20],
        [21, 22, 23, 21, 22, 23],
        [24, 25, 26, 24, 25, 26]]])

In [12]:
np.dstack((a, b)).shape

(3, 3, 6)